INF_CE/INF_CE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('indexapp.urls')),
    path('asignacion/', include('Asignacion.urls')),
    path('facturacion/', include('facturacion.urls')),
    path('proyectos/', include('proyectos.urls')),
    path('contratos/', include('contratos.urls')),
    path('select2/', include('django_select2.urls')),
    path('', include('login.urls')),
]

INF_CE/indexapp/urls.py
from django.urls import path
from . import views
# rutas de app
app_name = 'indexapp'

urlpatterns = [
    path('PRST/', views.CableoperadoresListView.as_view(), name='lista_cableoperadores'),
    path('PRST/<int:pk>/', views.cableoperador, name='detalle_cableoperador'),
    path('PRST/crear/', views.CableoperadoreCreateView.as_view(), name='crear_cableoperador'),
    path('PRST/<int:pk>/editar/', views.CableoperadoresUpdateView.as_view(), name='editar_cableoperador'),
]

INF_CE/login/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import inicio_sesion, home_view
# rutas de app
app_name = 'login'
urlpatterns = [
    path('login/', inicio_sesion, name='login'),
    path('logout/', LogoutView.as_view(next_page='login:login'), name='logout'),
    path('', home_view, name='home')
]

INF_CE/proyectos/urls.py
from django.urls import path
from . import views
# rutas de app
app_name = 'proyectos'

urlpatterns = [
    path('crear/', views.ProyectosCreateView.as_view(), name='crear_proyecto'),
    path('list/', views.ProyectosListView.as_view(), name='lista_proyectos'),
]

INF_CE/indexapp/models.py
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.
# Cableoperadores - Aqui va la tabla de los cableoperadores
Rliquidacion = [
    ('Calendarios', 'Calendarios'),
    ('Habiles', 'Habiles'),
]
ESTADOS_CONTRATO = [
    ('Contratado' , 'Contratado'),
    ('Finalizado' , 'Finalizado'),
    ('En_Renovacion' , 'En Renovacion'),
    ('Renovacion_firma_prst' , 'En Renovacion - Firma PRST'),
    ('Renovacion_firma_air_e' , 'En Renovacion - Firma AIR-E'),
    ('nuevo_firma_prst' , 'Nuevo - Firma PRST'),
    ('nuevo_firma_air_e' , 'Nuevo - Firma AIR-E'),
    ('En_Gestion' , 'En Gestion'),
    ('Sin_usos' , 'Sin Usos'),
]
class Cableoperadores(models.Model):
    nombre = models.CharField(max_length=100, unique=True, verbose_name='Nombre (Obligatorio)')
    nombre_largo = models.CharField(max_length=255, null=True, blank=True, unique=True)
    NIT = models.IntegerField(null=True, blank=True, unique=True)
    Digito_verificacion = models.IntegerField(null=True, blank=True, verbose_name='Digito de verificación')
    RegistroTic = models.BigIntegerField(null=True, blank=True, verbose_name='Registro TIC')
    CodigoInterno = models.BigIntegerField(null=True, blank=True, verbose_name='Codigo Interno')
    pais = models.CharField(max_length=100, null=True, blank=True)
    ciudad = models.CharField(max_length=100, null=True, blank=True)
    direccion = models.CharField(max_length=255, null=True, blank=True, verbose_name='Dirección')
    Representante = models.CharField(max_length=100, null=True, blank=True)
    telefono = models.BigIntegerField(verbose_name='Teléfono (Obligatorio)')
    correo = models.EmailField(max_length=100,verbose_name='Correo (Obligatorio)')
    ejecutiva = models.ForeignKey(User, on_delete=models.CASCADE)
    observaciones = models.TextField(max_length=1000, verbose_name='Observaciones (Obligatorio)')
    estado = models.CharField(max_length=100, choices=ESTADOS_CONTRATO, verbose_name='Estado (Obligatorio)')
    vencimiento_factura = models.PositiveIntegerField(null=True, blank=True)
    preliquidacion_num = models.PositiveIntegerField(null=True, blank=True, verbose_name='Preliquidacion Numero')
    preliquidacion_letra = models.CharField(max_length=100,null=True, blank=True, verbose_name='Preliquidacion Letra')
    respuesta_preliquidacion = models.CharField(choices=Rliquidacion, max_length=100,null=True, blank=True, verbose_name='Respuesta Preliquidacion')

    class Meta:
        db_table = "cableoperadores"
    def __str__(self):
        return self.nombre

INF_CE/indexapp/forms.py
from django import forms
from .models import Cableoperadores
from django.contrib.auth.models import User, Group
from django_select2.forms import Select2Widget


# Opciones para el campo de estado del proyecto
SHIFT_CHOICES = [
    ('1', 'En Progreso'),
    ('2', 'Completado'),
    ('3', 'Pendiente'),
]

    

class CableoperadoresModelForm(forms.ModelForm):
    class Meta:
        model = Cableoperadores
        fields = '__all__'
        exclude = ['ejecutiva']
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nombre del cableoperador'
            }),
            'nombre_largo': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nombre largo del cableoperador'
            }),
            'NIT': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'NIT del cableoperador'
            }),
            'Digito_verificacion': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Digito de verificación del cableoperador'
            }),
            'RegistroTic': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Registro TIC del cableoperador'
            }),
            'CodigoInterno': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Código interno del cableoperador'
            }),
            'pais': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Pais del cableoperador'
            }),
            'ciudad': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ciudad del cableoperador'
            }),
            'direccion': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Dirección del cableoperador'
            }),
            'Representante': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Representante del cableoperador'
            }),
            'telefono': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Telefono del cableoperador'
            }),
            'correo': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Correo del cableoperador'
            }),
            'observaciones': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Observaciones',
                'rows': 4,
            }),
            'estado': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Estado del cableoperador',
                'max_length': 100
            }),
            'vencimiento_factura': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Vencimiento de la factura'
            }),
            'preliquidacion_num': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Número de preliquidación'
            }),
            'preliquidacion_letra': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Letra de preliquidación',
                'max_length': 100
            }),
            'respuesta_preliquidacion': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Letra de preliquidación',
                'max_length': 100
            }),
            'ejecutiva': Select2Widget(attrs={
                'class': 'form-control'
            }),
        }

        
        

INF_CE/proyectos/forms.py
from django import forms
from .models import Proyectos
from django_select2.forms import Select2Widget
# Formulario con ModelForms
class ProyectosModelForm(forms.ModelForm):

    class Meta:
        model = Proyectos
        fields = '__all__'
        exclude = ['responsable']
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nombre del proyecto'
            }),
            'TipoIngreso': forms.Select(attrs={
                'class': 'form-control'
            }),
            'departamento': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Seleccione un departamento',
            }),
            'municipio': forms.Select(attrs={
                'class': 'form-control',
                'widget': Select2Widget
                
            }),
            'estado_ingreso': forms.Select(attrs={
                'class': 'form-control',
                'widget': Select2Widget
                
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'placeholder': 'Descripción del proyecto'
            }),
            'fecha_inicio': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control'
            }),
            'fecha_fin': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control'
            }),
            'fecha_radicacion': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control'
            }),
            'fecha_revision': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control'
            }),
            'tipo8': forms.NumberInput(attrs={
                'class': 'InputNumero'
            }),
            'tipo9': forms.NumberInput(attrs={
                'class': 'InputNumero'
            }),
            'tipo10': forms.NumberInput(attrs={
                'class': 'InputNumero'
            }),
            'tipo11': forms.NumberInput(attrs={
                'class': 'InputNumero'
            }),
            'tipo12': forms.NumberInput(attrs={
                'class': 'InputNumero'
            }),
            'tipo14': forms.NumberInput(attrs={
                'class': 'InputNumero'
            }),
            'tipo16': forms.NumberInput(attrs={
                'class': 'InputNumero'
            }),
            'cableoperador': Select2Widget
            
        }

INF_CE/indexapp/views.py
from django.shortcuts import render
from django.urls import reverse
from indexapp.forms import CableoperadoresModelForm
from indexapp.models import Cableoperadores
from contratos.models import Contratos
from facturacion.models import Facturacion
from django.views.generic import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def admin(request):
    return render(request,'indexapp/admin.html')

# 404
def error(request):
    return render(request, 'error.html')
         
# Clase de cableoperadores
# En tu views.py
class CableoperadoresListView(ListView):
    model = Cableoperadores
    template_name = 'indexapp/cableoperadorList.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        cableoperador_pk = self.request.GET.get('cableoperadorf') # Obtiene el PK del select
        
        if cableoperador_pk and cableoperador_pk != '':
            # 💡 Filtra por la clave primaria (pk)
            queryset = queryset.filter(pk=cableoperador_pk) 
            
        return queryset.order_by('nombre')
    # Continúa en tu views.py, dentro de CableoperadoresListView
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 💡 Pasa la lista de TODOS los cableoperadores para llenar el <select>
        context['cableoperadores'] = Cableoperadores.objects.all().order_by('nombre_largo') 
        return context
    
def cableoperador(request, pk=None):
    if pk:
        cableoperador = Cableoperadores.objects.get(pk=pk)
        facturas = Facturacion.objects.filter(Nombre_prst=cableoperador).order_by('-Fecha_fact')
        contrato = Contratos.objects.filter(cableoperador=cableoperador).first()
        object = {
            'object': cableoperador,
            'facturas': facturas,
            'contrato': contrato
        }
        return render(request, 'indexapp/cableoperador.html', object)


class CableoperadoreCreateView(LoginRequiredMixin,CreateView):
    model = Cableoperadores
    form_class = CableoperadoresModelForm
    template_name = 'indexapp/CableoperadoresForm.html'
    #success_url = '/index/PRST/'
    def form_valid(self, form):
        # 1. Accede al objeto User que está haciendo la solicitud.
        #    'self.request.user' contiene el objeto User logueado.
        current_user = self.request.user

        # 2. Asigna el objeto User al campo 'ejecutiva' de la instancia.
        #    Esto es crucial para un ForeignKey: ¡debes asignar el objeto!
        form.instance.ejecutiva = current_user

        # 3. Llama al método base para guardar el objeto y manejar la redirección.
        return super().form_valid(form)
    def get_success_url(self):
        # El objeto que se acaba de actualizar está disponible como self.object
        pk = self.object.pk
        return reverse('indexapp:detalle_cableoperador', kwargs={'pk': pk})

class CableoperadoresUpdateView(LoginRequiredMixin, UpdateView):
    model = Cableoperadores
    form_class = CableoperadoresModelForm
    template_name = 'indexapp/CableoperadoresForm.html'
    #success_url = '/index/PRST/'

    def get_success_url(self):
        # El objeto que se acaba de actualizar está disponible como self.object
        pk = self.object.pk
        
        # Usamos 'reverse' para construir la URL basándonos en el nombre de la ruta
        # y pasamos el pk como argumento de palabra clave (kwargs)
        return reverse('indexapp:detalle_cableoperador', kwargs={'pk': pk})

INF_CE/proyectos/views.py
from django.shortcuts import render
from .forms import ProyectosModelForm
from .models import Proyectos
from django.views.generic import CreateView, ListView
# Create your views here.
# vista del formulario de Proyectos
class ProyectosCreateView(CreateView):
    model = Proyectos
    form_class = ProyectosModelForm
    template_name = 'proyectos/ProyectosForm.html'
    success_url = 'proyectos/ProyectosForm.html'
    def form_valid(self, form):
        # 1. Obtener el objeto User logueado
        user = self.request.user

        # 2. Construir el nombre completo (nombre y apellido)
        full_name = f"{user.first_name} {user.last_name}".strip()

        # 3. Asignar el valor al campo 'responsable' de la instancia
        form.instance.responsable = full_name
        
        # 4. Llamar al método base para guardar el objeto
        return super().form_valid(form)
    
# vista para listar los proyectos
class ProyectosListView(ListView):
    model = Proyectos
    template_name = 'proyectos/ProyectosList.html'
    def get_queryset(self):
        queryset = super().get_queryset()
        cableoperador = self.request.GET.get('cableoperadorf')
        if cableoperador:
            queryset = queryset.filter(cableoperador__nombre=cableoperador)
        return queryset.order_by('-fecha_radicacion')

INF_CE/INF_CE/templates/indexapp/CableoperadoresForm.html
<!-- Se carga la plantilla base -->
{% extends 'base.html' %} <!-- ruta de la plantilla base -->
{% load static %} <!-- Se cargan los script e imagenes -->

<!--Titulo de la pestaña-->
{% block Title_head %}
<title>Air-e | Cargar Proyectos</title>
{% endblock %}
<!--Este es el titulo de la cabecera-->
{% block title %}
<span class="h2 align-middle ms-3 admin">Registrar Cableoperadores</span>
{% endblock %}
<!--Este es el contenido de esta sesion llamada administrador-->
{% block content %}
<!--Formulario para registrar cableoperadores-->
<div class="container mt-4 mb-2 bg-info-subtle text-info-emphasis border-3 border border-primary-subtle">
    <center><h2>Registrar Nuevo Cableoperador</h2></center>
    <form method="post" action="">
    {% csrf_token %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {{ form.media }}
    <div class="row g-3"> <div class="col-md-3" style="font-weight: 700;">
            {{ form.nombre.label_tag }} {{ form.nombre }}           {% if form.nombre.errors %}{{ form.nombre.errors }}{% endif %}
        </div>
        <div class="col-md-3"   style="font-weight: 700;">
            {{ form.nombre_largo.label_tag }}
            {{ form.nombre_largo }}
            {% if form.nombre_largo.errors %}{{ form.nombre_largo.errors }}{% endif %}
        </div>
        <div class="col-md-2" style="font-weight: 700;">
            {{ form.NIT.label_tag }}
            {{ form.NIT }}
            {% if form.NIT.errors %}{{ form.NIT.errors }}{% endif %}
        </div>    
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.Digito_verificacion.label_tag }}
            {{ form.Digito_verificacion }}
            {% if form.Digito_verificacion.errors %}{{ form.Digito_verificacion.errors }}{% endif %}
        </div>
        <div class="col-md-2" style="font-weight: 700;">
            {{ form.RegistroTic.label_tag }}
            {{ form.RegistroTic }}
            {% if form.RegistroTic.errors %}{{ form.RegistroTic.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.CodigoInterno.label_tag }}
            {{ form.CodigoInterno }}
            {% if form.CodigoInterno.errors %}{{ form.CodigoInterno.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.pais.label_tag }}
            {{ form.pais }}
            {% if form.pais.errors %}{{ form.pais.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.ciudad.label_tag }}
            {{ form.ciudad }}
            {% if form.ciudad.errors %}{{ form.ciudad.errors }}{% endif %}
        </div>
        <div class="col-md-2" style="font-weight: 700;">
            {{ form.direccion.label_tag }}
            {{ form.direccion }}
            {% if form.direccion.errors %}{{ form.direccion.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.telefono.label_tag }}
            {{ form.telefono }}
            {% if form.telefono.errors %}{{ form.telefono.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.correo.label_tag }}
            {{ form.correo }}
            {% if form.correo.errors %}{{ form.correo.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.Representante.label_tag }}
            {{ form.Representante }}
            {% if form.Representante.errors %}{{ form.Representante.errors }}{% endif %}
        </div>
        <div class="col-md-2" style="font-weight: 700;">
            {{ form.estado.label_tag }}
            {{ form.estado }}
            {% if form.estado.errors %}{{ form.estado.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.vencimiento_factura.label_tag }}
            {{ form.vencimiento_factura }}
            {% if form.vencimiento_factura.errors %}{{ form.vencimiento_factura.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.preliquidacion_num.label_tag }}
            {{ form.preliquidacion_num }}
            {% if form.preliquidacion_num.errors %}{{ form.preliquidacion_num.errors }}{% endif %}
        </div>
        <div class="col-md-3" style="font-weight: 700;">
            {{ form.preliquidacion_letra.label_tag }}
            {{ form.preliquidacion_letra }}
            {% if form.preliquidacion_letra.errors %}{{ form.preliquidacion_letra.errors }}{% endif %}
        </div>
        <div class="col-md-6" style="font-weight: 700;">
            {{ form.respuesta_preliquidacion.label_tag }}
            {{ form.respuesta_preliquidacion }}
            {% if form.respuesta_preliquidacion.errors %}{{ form.respuesta_preliquidacion.errors }}{% endif %}
        </div>
        <div class="col-md-6" style="font-weight: 700;">
            {{ form.observaciones.label_tag }}
            {{ form.observaciones }}
            {% if form.observaciones.errors %}{{ form.observaciones.errors }}{% endif %}
        </div>
        
        
    </div>
    <center class="mt-4">
    <button type="submit" class="btn btn-primary border border-light border border-2">Guardar<a href="{% url 'indexapp:lista_cableoperadores' %}"></a></button>
    </center>
</form>
</div>

<center>
    <button type="submit" class="btn btn-primary border border-light border border-2">
    <a class="text-white text-decoration-none" href="{% url 'indexapp:lista_cableoperadores' %}">Volver a lista de cable operadores</a>
   </button>
</center>
<div class="col-6"></div>
{% endblock %} 

INF_CE/INF_CE/templates/indexapp/ProyectosForm.html
<!-- Se carga la plantilla base -->
{% extends 'base.html' %} <!-- ruta de la plantilla base -->
{% load static %} <!-- Se cargan los script e imagenes -->

<!--Titulo de la pestaña-->
{% block Title_head %}
<title>Air-e | Cargar Proyectos</title>
{% endblock %}
<!--Este es el titulo de la cabecera-->
{% block title %}
<span class="h2 align-middle ms-3 admin">Cargar Proyectos</span>
{% endblock %}
<!--Este es el contenido de esta sesion llamada administrador-->
{% block content %}
<!--Formulario para registrar proyectos-->
<strong><div class="container mt-4 col-4">
    <h2>Registrar Nuevo Proyecto</h2>
    <form method="post" action="">
        {% csrf_token %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script><!--para que salga la barra de busqueda-->
        {{ form.media }} <!-- ¡Esta línea es crucial! -->
        <table>
            {{ form.as_p }}
        </table>
        <center>
        <button type="submit" class="btn btn-primary">Guardar Proyecto</button>
        </center>
    </form>
</div>
<div class="col-6"></div></strong>
{% endblock %} 

INF_CE/INF_CE/templates/indexapp/cableoperadorList.html
<!-- Versión mejorada del template con cards para móviles -->
{% extends 'base.html' %}
{% load static %}

<!--Titulo de la pestaña-->
{% block Title_head %}
<title>Air-e | PRST</title>
<link rel="stylesheet" href="{% static 'ProyectosList.css' %}">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock %}

<!--Este es el titulo de la cabecera-->
{% block title %}
<span class="h2 align-middle ms-3 admin">Lista de cableoperadores</span>
{% endblock %}

<!--Este es el contenido de esta sesion llamada administrador-->
{% block content %}
<!-- Sección de filtros -->
<div class="filter-section bg-white text-dark border-2">
    <form method="get" action="." class="d-flex align-items-end gap-2 flex-wrap bg-white text-dark ">
    <div class="flex-grow-1">
        <select name="cableoperadorf" id="cableoperadorf" class="filter-input ">
            <option value="">Seleccionar cableoperador...</option>
            {% for cableoperador in cableoperadores %}
            <option value="{{ cableoperador.pk }}" 
                {% if cableoperador.pk|stringformat:"s" == request.GET.cableoperadorf|default:""|stringformat:"s" %}selected{% endif %}>
                {{ cableoperador.nombre_largo }}
            </option>
            {% endfor %}
        </select>
        
        <button type="submit" class="filter-btn border border-warning-subtle border border-5" style="font-weight: 700;">Aplicar Filtro</button>
    </div>
    <a href="{% url 'indexapp:crear_cableoperador' %}" class="btn btn-primary border border-warning-subtle border border-5" style="font-weight: 700;">Crear nuevo cableoperador</a>
</form>

<script>
    $(document).ready(function() {
        // Aplica Select2 al campo
        $('#cableoperadorf').select2({
             placeholder: 'Escribe para buscar un cableoperador...',
             allowClear: true 
        });
    });
</script>

</div>
<!-- Vista de tabla para desktop -->
<div class="row">
    <div>
        <h2 class="p-3 mb-2 bg-primary-subtle text-primary-emphasis text-center border border-info ">Lista de cableoperadores</h2>
    </div>
    <div class="row g-3 items-center"> {% for object in object_list %}
       <div class="col-lg-6">
            <div class="card mb-3 shadow-sm">
                <div class="p-3 mb-2 bg-secondary text-white border-4 ">
                    <h3 class="text-center" style="font-weight: 700;">{{ object.nombre }}</h3>
                </div>
                <div class="card-body">
                    <div class="row g-2">
                        <div class="col-6">
                            <small class="text-muted" style="font-weight: 700;">NIT:</small><br>
                            <span class="fw-semibold">{{ object.NIT }}</span>
                        </div>
                        <div class="col-6">
                            <small class="text-muted" style="font-weight: 700;">País:</small><br>
                            <span class="fw-semibold">{{ object.pais }}</span>
                        </div>
                        <div class="col-6">
                            <small class="text-muted" style="font-weight: 700;">Código interno:</small><br>
                            <span class="fw-semibold">{{ object.CodigoInterno }}</span>
                        </div>
                        <div class="col-6">
                            <button>
                               <strong><a href="{% url 'indexapp:detalle_cableoperador' pk=object.pk %}">ver mas</a></strong>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div colspan="18" class="text-center py-4">
            <em>No se encontraron cableoperadores</em>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

INF_CE/INF_CE/templates/indexapp/cableoperadorUpdate.html
<!-- Se carga la plantilla base -->
{% extends 'base.html' %} <!-- ruta de la plantilla base -->
{% load static %} <!-- Se cargan los script e imagenes -->

<!--Titulo de la pestaña-->
{% block Title_head %}
<title>Air-e | Cargar Proyectos</title>
{% endblock %}
<!--Este es el titulo de la cabecera-->
{% block title %}
<span class="h2 align-middle ms-3 admin">Registrar Cableoperadores</span>
{% endblock %}
<!--Este es el contenido de esta sesion llamada administrador-->
{% block content %}
<!--Formulario para registrar cableoperadores-->
<div class="container mt-4 col-4">
    <center><h2>Registrar Nuevo Cableoperador</h2></center>
    <form method="post" action="">
        {% csrf_token %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script><!--para que salga la barra de busqueda-->
        {{ form.media }} <!-- ¡Esta línea es crucial! -->
        <strong><table>
            {{ form.as_p }}
        </table>
        </strong>
        <center>
        <button type="submit" class="btn btn-primary">Guardar<a href="{% url 'indexapp:detalle_cableoperador' pk=object.pk %}"></a></button>
        </center>
    </form>
</div>
<center>
          <div class="d-flex justify-content-center mt-4"></div>
          <button type="submit" class="btn btn-primary">
            <a class="text-white" href="{% url 'indexapp:lista_cableoperadores' %}">Ir a lista de cable operadores</a>
        </div>
    </button>
</center>
<div class="col-6"></div>
{% endblock %} 