INF_CE/Asignacion/urls.py
from django.urls import path
from . import views
from django.contrib.auth.models import User
# rutas de app

app_name = 'asignacion'

urlpatterns = [
    path('asignar/', views.Asignacion_proyectosCreateView.as_view(), name='AsignacionCreate'),
    path('asignado/', views.Asignacion_proyectosListView.as_view(), name='AsignacionList'),
]

INF_CE/INF_CE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('indexapp.urls')),
    path('asignacion/', include('Asignacion.urls')),
    path('facturacion/', include('facturacion.urls')),
    path('proyectos/', include('proyectos.urls')),
    path('contratos/', include('contratos.urls')),
    path('select2/', include('django_select2.urls')),
    path('', include('login.urls')),
]

INF_CE/contratos/urls.py
from django.urls import path
from . import views
# rutas de app
app_name = 'contratos'

urlpatterns = [
    # URL para crear un nuevo Contrato (y sus recursos)
    path('', views.crear_contrato_con_recursos, name='crear_contrato'),
    # URL de ejemplo para la redirección
    path('lista/', views.lista_contratos, name='lista_contratos'),
    path('<int:pk>/', views.detalle_contrato, name='detalle_contrato'),
    path('lista/<int:pk>/', views.detalle_contrato_elegido, name='detalle_contrato_elegido'),
       # 1. URL para Creación Independiente (Sin PK)
    path('crear/', views.crear_contrato_con_recursos, name='crear_contrato_independiente'),
    
    # 2. URL para Creación Vinculada (Con PK)
    path('crear/<int:pk>/', views.crear_contrato_con_recursos, name='crear_contrato_vinculado'),
    # contratos/urls.py

    # ... otras URLs ...
    path('editar/<int:pk>/', views.actualizar_contrato_con_recursos, name='actualizar_contrato'),

]

INF_CE/indexapp/urls.py
from django.urls import path
from . import views
# rutas de app
app_name = 'indexapp'

urlpatterns = [
    path('PRST/', views.CableoperadoresListView.as_view(), name='lista_cableoperadores'),
    path('PRST/<int:pk>/', views.cableoperador, name='detalle_cableoperador'),
    path('PRST/crear/', views.CableoperadoreCreateView.as_view(), name='crear_cableoperador'),
    path('PRST/<int:pk>/editar/', views.CableoperadoresUpdateView.as_view(), name='editar_cableoperador'),
]

INF_CE/login/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import inicio_sesion, home_view
# rutas de app
app_name = 'login'
urlpatterns = [
    path('login/', inicio_sesion, name='login'),
    path('logout/', LogoutView.as_view(next_page='login:login'), name='logout'),
    path('', home_view, name='home')
]

INF_CE/proyectos/urls.py
from django.urls import path
from . import views
# rutas de app
app_name = 'proyectos'

urlpatterns = [
    path('crear/', views.ProyectosCreateView.as_view(), name='crear_proyecto'),
    path('list/', views.ProyectosListView.as_view(), name='lista_proyectos'),
]

INF_CE/INF_CE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Mod_Admin.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'logo-aire-intervenida.png' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    {% block Title_head %}
    {% endblock %}
</head>
<body>
    <!--Header-->
    <div class="top-bar bg-info border-bottom p-2">
        <button class="btn btn-success sidebar-toggle-btn" id="toggleSidebar">☰</button>
        <a href="{% url 'login:home' %}"><img src="{% static 'aire.png' %}" style="height: 40px; width: auto; float: right;" alt="Logo de AIR-E" class="logo-aire"></a>
        {% block title %}
        {% endblock %}
    </div>
    <!--End of header-->
    <!--Barra de navegacion-->
    <div class="main-wrapper d-flex" style="min-height: 100vh;">
        <nav id="sidebar" class="sidebar sidebar-collapsed" style="background-color: #0f62fc; color: #000;">
            <!-- Aquí va el bloque de menú que te generé -->
            <ul class="nav flex-column">
                <li class="nav-item mb-2">
                    <a href="{% url 'login:home' %}">
                        <span class="sidebar-icon">🏠</span>
                        <span class="sidebar-text text-white">Inicio</span>
                    </a>
                </li>
                <li class="nav-item mb-2">
                    <a href="{% url 'indexapp:lista_cableoperadores' %}">
                        <span class="sidebar-icon">🔌</span>
                        <span class="sidebar-text text-white">Cableoperadores</span>
                    </a>
                </li>
                <li class="nav-item mb-2">
                    <a href="{% url 'asignacion:AsignacionList' %}">
                        <span class="sidebar-icon">🗂️</span>
                        <span class="sidebar-text text-white">Asignados</span>
                    </a>
                </li>
                <li class="nav-item mb-2">
                    <a href="{% url 'asignacion:AsignacionCreate' %}">
                        <span class="sidebar-icon">⚙️</span>
                        <span class="sidebar-text text-white">Crear Asignación</span>
                    </a>
                </li>
                <li class="nav-item mb-2">
                    <a href="{% url 'proyectos:lista_proyectos' %}">
                        <span class="sidebar-icon">📋</span>
                        <span class="sidebar-text text-white">Lista de Proyectos</span>
                    </a>
                </li>
                <li class="nav-item mb-2">
                    <a href="{% url 'proyectos:crear_proyecto' %}">
                        <span class="sidebar-icon">🆕</span>
                        <span class="sidebar-text text-white">Crear Proyecto</span>
                    </a>
                </li>
                <li class="nav-item mb-2">
                    <a href="{% url 'facturacion:lista_facturacion' %}">
                        <span class="sidebar-icon">🧾</span>
                        <span class="sidebar-text text-white">Facturacion</span>
                    </a>
                </li>
                <li class="nav-item mb-2">
                    <a href="{% url 'contratos:lista_contratos' %}">
                        <span class="sidebar-icon">🧾</span>
                        <span class="sidebar-text text-white">Contratos</span>
                    </a>
                </li>
                <br><br>
                <li class="nav-item mb-2">
                        {% if user.is_authenticated %}
                            <span class="sidebar-text text-white">👨‍💼Usuario: </span>
                            <span class="sidebar-text text-white">{{ user.username }}</span><br>
                        {% endif %}
                        <form action="{% url 'login:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="sidebar-text text-white bg-secondary"><span class="sidebar-icon">🚪</span>Cerrar sesión</button>
                        </form>
                    </a>
                </li>   
            </ul>
        </nav>
    
        <!--Fin de barra de navegacion-->
        <div class="sidebar-overlay" id="sidebarOverlay"></div>
            <main class="content">
                {% block content %}{% endblock %}
            </main>
    </div>
        <!--Pie de pagina-->
        {% include 'partials/footer.html' %}
        <!--Fin de pie de pagina-->
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'script.js' %}"></script>
</html>

INF_CE/INF_CE/templates/error.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'error.css' %}">
    <title>Página no encontrada</title>
    <link rel="icon" type="image/x-icon" href="{% static 'logo-aire-intervenida.png' %}">
</head>
<body>
    <h1 class="gradient-text">¡Ups! Página no encontrada</h1>
    <p class="gradient-text">Lo sentimos, la página que buscas no existe. </p>
    <div class="codigo-error gradient-text">404</div>
  <div class="contenido-principal">
     <a href="/" class="btn-volver-inicio gradient-text">Volver a la página de inicio</a>
  </div>
  <p class="descripcion background-color-negro gradient-text">Somos una empresa dedicada a la distribución de energía eléctrica, comprometida con la calidad y el servicio a nuestros clientes.</p>
</body>
</html>